# Installs Node.js dependencies and Yarn, and checks formatting + linting

name: Lint Node.js

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - "src-tauri/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Node.js LTS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies from yarn.lock
        run: yarn install --frozen-lockfile

      - name: Run lint step
        run: yarn lint
